### ISSUE TITLE
Duplicated lines in console buffer

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [pycontribs/enrich#39] opened 2022-08-10 06:01 UTC
While testing enrich in an environment with rich 12.5.1 installed, I'm seeing duplicated text in the console buffer, and I'm struggling to work out how this happens. Test failure is below:

```
[    4s]     def test_rich_console_ex() -> None:
[    4s]         """Validate that ConsoleEx can capture output from print() calls."""
[    4s]         console = Console(record=True, redirect=True)
[    4s]         console.print("alpha")
[    4s]         print("beta")
[    4s]         sys.stdout.write("gamma\n")
[    4s]         sys.stderr.write("delta\n")
[    4s]         # While not supposed to happen we want to be sure that this will not raise
[    4s]         # an exception. Some libraries may still sometimes send bytes to the
[    4s]         # streams, notable example being click.
[    4s]         # sys.stdout.write(b"epsilon\n")  # type: ignore
[    4s]         text = console.export_text()
[    4s] >       assert text == "alpha\nbeta\ngamma\ndelta\n"
[    4s] E       AssertionError: assert 'alpha\nbeta\...elta\ndelta\n' == 'alpha\nbeta\ngamma\ndelta\n'
[    4s] E           alpha
[    4s] E           beta
[    4s] E         + beta
[    4s] E         + gamma
[    4s] E           gamma
[    4s] E           delta
[    4s] E         + delta
[    4s] 
[    4s] src/enrich/test/test_console.py:23: AssertionError
```

**Comment by ssbarnea** [comment] 2022-10-04 11:03
Duplicate of #40

**Closed by ssbarnea** 2022-10-04 11:03 UTC
