### ISSUE TITLE
Support messages with newlines

### ISSUE THREAD

**Issue by jdumas** [pycontribs/enrich#23] opened 2021-02-27 01:58 UTC
It seems the FluidLogRender doesn't work well with messages containing newlines:

```python
import logging
from enrich.logging import RichHandler

logging.basicConfig(level="INFO", handlers=[RichHandler()])

log = logging.getLogger("rich")
log.info("Text that we\ndo not want\npre-wrapped by logger: %s", 100 * "x")
```

**Comment by ssbarnea** [comment] 2021-03-16 11:56
PR to fix is welcomed.

**Comment by ssbarnea** [comment] 2021-12-29 11:09
Now that I read the bug again I realise that I should close this as won'tfix, mainly because you cannot have both fluid newlines and reindentation of newlines.

If you log anything with newlines, you should know well that only the first line will container the prefix columns. That is true even for other loggers, not a bug of this library.

**Closed by ssbarnea** 2021-12-29 11:09 UTC
Labels: bug
